services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/apache/000.conf:/etc/apache2/sites-available/000.conf
      - ./docker/php/php.ini:/etc/php/8.3/apache2/php.ini
      - ./docker/php/xdebug.ini:/etc/php/8.3/mods-available/xdebug.ini
    networks:
      - panel
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3309:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'dev'
      MYSQL_USER: 'sail'
      MYSQL_PASSWORD: '1234'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - './docker/database:/var/lib/mysql'
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p1234'
      retries: 3
      timeout: 5s
    networks:
      - panel
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      PMA_HOSTS: mysql
    ports:
      - 7000:80
    depends_on:
      - mysql
    networks:
      - panel
networks:
  panel:
    driver: bridge